nodeLinker: node-modules

enableGlobalCache: false

npmMinimalAgeGate: 14d

npmPublishAccess: public

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  pendle:
    npmAlwaysAuth: true
    npmAuthToken: "${BOROS_MCP_NPM_AUTH_TOKEN}"
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

unsafeHttpWhitelist:
  - registry.npmjs.org

yarnPath: .yarn/releases/yarn-4.13.0.cjs
