name: Release snapshot package

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ${{ github.ref }}
    outputs:
      package_version:
        description: "Package version"
        value: ${{ jobs.release.outputs.package_version }}
    secrets:
      NPM_PUBLISH_TOKEN:
        required: true

permissions:
  contents: read

concurrency:
  group: snapshot-${{ github.workflow }}-${{ inputs.ref || github.ref }}
  cancel-in-progress: true

jobs:
  release:
    if: github.repository == 'pendle-finance/boros-mcp'
    environment: npm-registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      REF: ${{ inputs.ref || github.ref }}
      BRANCH_NAME: ${{ inputs.ref || github.head_ref || github.ref_name }}
      BOROS_MCP_NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    outputs:
      package_version: ${{ steps.changeset_prepare.outputs.package_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.REF }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Prepare changeset snapshot version
        id: changeset_prepare
        run: |
          yarn changeset version --snapshot "${BRANCH_NAME##*/}"
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          echo "$PACKAGE_VERSION"
          echo "package_version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Create snapshot release
        uses: changesets/action@v1
        with:
          publish: yarn release --tag snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
